---
# GTTS tasks
- name: Create Docker network yourvps_shared
  community.docker.docker_network:
    name: yourvps_shared
  tags: gtts

- name: Ensure GTTS directories exist
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ gtts_dir }}"
    - "{{ gtts_app_path }}"
  tags: gtts

- name: Deploy GTTS docker-compose
  template:
    src: gtts.compose.yml.j2
    dest: "{{ gtts_dir }}/docker-compose.yml"
    mode: '0644'
  notify: restart gtts
  tags: gtts

- name: Copy Python file for GTTS API
  copy:
    src: main.py
    dest: "{{ gtts_app_path }}/main.py"
    mode: '0644'
  notify: restart gtts
  tags: gtts

- name: Ensure GTTS is running (docker compose up -d)
  shell: |
    cd {{ gtts_dir }} && docker compose up -d
  tags: gtts
